CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    uuid TEXT NOT NULL UNIQUE,
    avatar_url TEXT,
    nickname TEXT,
    real_name TEXT,
    class TEXT,
    class_type TEXT,
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    current_status TEXT,
    last_login_at TIMESTAMP,
    last_login_ip TEXT,
    score INTEGER DEFAULT 0,
    user_role TEXT,
    title TEXT,
    invited_by TEXT,
    views INTEGER DEFAULT 0,
    other_info JSONB,
    is_verified BOOLEAN
);